### ISSUE TITLE
Cursor alert invalid key

### ISSUE THREAD

**Issue by yuchaozhou** [ryoppippi/curxy#15]
## Start Server Command
OPENAI_API_KEY=sk-123456 deno run -A jsr:@ryoppippi/curxy

## API ACCESS NORMAL
curl https://pn-circus-parental-should.trycloudflare.com/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer sk-123456" -d '{
  "messages": [
    {
      "role": "system",
      "content": "You are a test assistant."
    },
    {
      "role": "user",
      "content": "Testing. Just say hi and nothing else."
    }
  ],
  "model": "qwen2.5-coder:7b"
}'
{"id":"chatcmpl-603","object":"chat.completion","created":1726741526,"model":"qwen2.5-coder:7b","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"Hi"},"finish_reason":"stop"}],"usage":{"prompt_tokens":28,"completion_tokens":2,"total_tokens":30}}

## Cursor ERROR
![WX20240919-182648](https://github.com/user-attachments/assets/6c00a7a9-24ed-44ff-a69a-c9b8b5013129)
![WX20240919-182914](https://github.com/user-attachments/assets/fa0d8c83-3baf-4261-8e67-2fdd57719630)

## CURSOR INFO
Version: 0.40.4
VSCode Version: 1.91.1
Commit: 63dae81aea2c3fc079420fe72578a8eef26ba870
Date: 2024-09-05T02:52:05.660Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.1.0

THX!

**Comment by pedh** [comment]
Confirmed. Cursor uses HTTP OPTIONS requests to identify supported HTTP methods, which are not supported by Ollama. This issue needs to be addressed in Curxy, as the original problem https://github.com/ollama/ollama/issues/3746 persists.

**Comment by ryoppippi** [comment]
@pedh Thank you for your debugging!
