### ISSUE TITLE
Model does not work with my plan

### ISSUE THREAD

**Issue by pedrosimao** [ryoppippi/curxy#19]
Hello,

I am trying to use `qwen2.5-coder` via ollama server.

I am getting a weird error message, below:

```
The model qwen2.5-coder does not work with your current plan or api key
```

The whole idea of using curxy is not to pay for a plan, and run it locally.
Any extra step I need.
I also didn't understand the advantage of setting OPENAI API key as a env variable.

**Comment by ryoppippi** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
