### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by wwjCMP** [ryoppippi/curxy#26]
Access to fetch at 'https://creature-bugs-cj-beginner.trycloudflare.com/v1/chat/completions' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jincdream** [comment]
https://github.com/ryoppippi/curxy/issues/27#issuecomment-2530652026
